# Generated by Django 4.2.16 on 2024-11-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_examples", "0004_remove_student_courses_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("date_of_birth", models.DateField()),
                (
                    "father",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="father_person",
                        to="db_examples.familyperson",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mother_person",
                        to="db_examples.familyperson",
                    ),
                ),
            ],
        ),
    ]
