# Generated by Django 4.2.16 on 2024-11-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_examples", "0005_familyperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyperson",
            name="father",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="father_person",
                to="db_examples.familyperson",
            ),
        ),
        migrations.AlterField(
            model_name="familyperson",
            name="mother",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mother_person",
                to="db_examples.familyperson",
            ),
        ),
    ]
